[package]
name = "kaudio"
version = "0.1.0"
edition = "2024"

[dependencies]
kasset = { path = "../kasset" }
kcore = { path = "../kcore" }
klog = { path = "../klog" }
kmath = { path = "../kmath" }
cpal = "0.18"
parking_lot = "0.12.5"
symphonia = { version = "0.6", default-features = false, features = ["wav", "vorbis", "ogg", "pcm"] }
