[package]
name = "kscript"
version = "0.1.0"
edition = "2024"

[dependencies]
kasset = { path = "../kasset" }
kcore = { path = "../kcore" }
klog = { path = "../klog" }
kmath = { path = "../kmath" }
kscene = { path = "../kscene" }
kphysics = { path = "../kphysics" }
fxhash = "0.2.1"
boa_engine = "0.21"

[dev-dependencies]
kparticle = { path = "../kparticle" }
