[package]
name = "kapp"
version = "0.1.0"
edition = "2024"

[dependencies]
kasset = { path = "../kasset" }
kaudio = { path = "../kaudio" }
kinput = { path = "../kinput" }
klog = { path = "../klog" }
krender = { path = "../krender" }
kmath = { path = "../kmath" }
# 环境捕获的产物是一张 HDR 全景图。
kpbr = { path = "../kpbr" }
kscene = { path = "../kscene" }
kui = { path = "../kui" }
kscript = { path = "../kscript" }
kwinit = { path = "../kwinit" }
pollster = "1.0.1"
winit = "0.30.13"
