[workspace]
members = [
    "src/kasset",
    "src/kcamera",
    "src/kcore",
    "src/kcore-derive",
    "src/kinput",
    "src/klog",
    "src/kgltf",
    "src/kmaterial",
    "src/kmesh",
    "src/kmath",
    "src/kshader",
    "src/ktask",
    "src/ktexture",
]

[package]
name = "kengine"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
kasset = { path = "src/kasset" }
kcamera = { path = "src/kcamera" }
kcore = { path = "src/kcore" }
kinput = { path = "src/kinput" }
klog  = { path = "src/klog" }
kgltf = { path = "src/kgltf" }
kmaterial = { path = "src/kmaterial" }
kmesh = { path = "src/kmesh" }
kmath = { path = "src/kmath" }
kshader = { path = "src/kshader" }
ktask = { path = "src/ktask" }
ktexture = { path = "src/ktexture" }
pollster = "1.0.1"
wgpu = "30.0.0"
winit = "0.30.13"

